# test_lvs_comprehensive.ps1
# Systematic LVS test: 25+ cases, both engines, real netlist.
# Run: .\test_lvs_comprehensive.ps1

param([string]$VygesBin = "$env:USERPROFILE\.cargo\bin\vyges-lvs.exe")

$ErrorActionPreference = "Stop"

# Baseline — structural MATCH with all nets renamed
$LAYOUT = @"
// Spectre hierarchical netlist generated by mmo-chip
.subckt lm2937 (Net_1 Net_5 Net_6 Net_7 Net_9 Net_10 Net_11 Net_12 Net_14 Net_19
Net_20 Net_21 Net_22 Net_23 Net_27 Net_28 Net_29 Net_3 Net_30 Net_33 Net_35
Net_37 Net_39 Net_4 Net_40 net2010 net2011 net2030 net2031 net2050 net2060
net2070 net2091 net2100 net2101 net2102 net2110 net2111 net2142 net2150 net2180
net2200 net2201 net2300 VDD GND)
  R1 (Net_5 Net_6) resistor r=3981
  R2 (net2010 net2011) resistor r=3981
  R3 (Net_7 Net_6) resistor r=3981
  R4 (net2030 net2031) resistor r=3981
  R5 (Net_7 Net_9) resistor r=3981
  R6 (net2050 Net_9) resistor r=3981
  Q101 (net2060 Net_19 GND 0) npn m=1.13
  Q102 (net2070 Net_19 GND 0) npn m=1.13
  Q3 (Net_1 Net_4 Net_3 0) pnp m=5
  Q4 (GND net2091 Net_3 0) pnp m=1.93
  Q103 (net2100 net2101 net2102 0) pnp m=1.93
  Q6 (net2110 net2111 Net_5 0) pnp m=2.03
  Q7 (Net_9 Net_12 Net_10 0) pnp
  Q8 (Net_11 Net_11 Net_10 0) pnp m=1.36
  Q9 (Net_14 Net_40 net2142 0) npn m=1.29
  R7 (net2150 Net_14) resistor r=6
  Q10 (Net_37 Net_35 Net_22 0) npn m=1.06
  Q11 (Net_35 Net_35 GND 0) npn m=5
  Q12 (net2180 Net_37 GND 0) npn m=5
  Q13 (Net_40 Net_28 GND 0) npn m=5
  Q14 (net2200 net2201 GND 0) npn m=5
  C1 (Net_23 Net_27) capacitor c=34570.868f
  R8 (Net_22 Net_29) resistor r=3887
  R9 (GND Net_33) resistor r=3887
  R10 (Net_21 Net_30) resistor r=3887
  R11 (GND Net_30) resistor r=3887
  R12 (Net_20 Net_33) resistor r=3887
  R13 (GND Net_29) resistor r=3887
  R14 (Net_39 GND) resistor r=915
  R15 (Net_39 GND) resistor r=892
  Q15 (net2300 Net_39 GND 0) npn m=1.41
  Q16 (Net_40 Net_12 Net_10 0) pnp m=1.1
.ends lm2937
"@

# Schematic baseline: structurally identical, all nets renamed
$SCHEMATIC = @"
.subckt lm2937 (n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 n11 n12 n13 n14 n15 n16 n17
n18 n19 n20 n21 n22 n23 n24 n25 n26 n27 n28 n29 n30 n31 n32 n33 n34 n35 n36
n37 n38 n39 n40 n41 n42 n43 n44 n45 n46 n47 n48 n49 n50 VDD GND)
  R1 (n5 n6) resistor r=3981
  R2 (n1 n2) resistor r=3981
  R3 (n7 n6) resistor r=3981
  R4 (n3 n4) resistor r=3981
  R5 (n7 n8) resistor r=3981
  R6 (n9 n8) resistor r=3981
  Q101 (n10 n11 GND 0) npn m=1.13
  Q102 (n12 n11 GND 0) npn m=1.13
  Q3 (n13 n14 n15 0) pnp m=5
  Q4 (GND n16 n15 0) pnp m=1.93
  Q103 (n17 n18 n19 0) pnp m=1.93
  Q6 (n20 n21 n5 0) pnp m=2.03
  Q7 (n8 n22 n23 0) pnp
  Q8 (n24 n24 n23 0) pnp m=1.36
  Q9 (n25 n26 n27 0) npn m=1.29
  R7 (n28 n25) resistor r=6
  Q10 (n29 n30 n31 0) npn m=1.06
  Q11 (n30 n30 GND 0) npn m=5
  Q12 (n32 n29 GND 0) npn m=5
  Q13 (n26 n33 GND 0) npn m=5
  Q14 (n34 n35 GND 0) npn m=5
  C1 (n36 n37) capacitor c=34570.868f
  R8 (n31 n38) resistor r=3887
  R9 (GND n39) resistor r=3887
  R10 (n40 n41) resistor r=3887
  R11 (GND n41) resistor r=3887
  R12 (n42 n39) resistor r=3887
  R13 (GND n38) resistor r=3887
  R14 (n43 GND) resistor r=915
  R15 (n43 GND) resistor r=892
  Q15 (n44 n43 GND 0) npn m=1.41
  Q16 (n26 n22 n23 0) pnp m=1.1
.ends lm2937
"@

# ── Test helpers ───────────────────────────────────────────────
$testCount = 0
$passCount = 0
$failCount = 0
$results = @()

function New-TempDir { $p = Join-Path $env:TEMP "lvs_comp_$(Get-Random)"; mkdir $p -Force | Out-Null; return $p }
function Remove-TempDir { param($p) if (Test-Path $p) { Remove-Item -LiteralPath $p -Recurse -Force -ErrorAction SilentlyContinue } }

function Run-Vyges {
  param([string]$LayoutContent, [string]$SchematicContent)
  $tmp = New-TempDir
  $l = Join-Path $tmp "layout.spice"; $s = Join-Path $tmp "schematic.spice"
  $j = Join-Path $tmp "job.lvs"; $o = Join-Path $tmp "result.json"
  try {
    $LayoutContent | Set-Content -LiteralPath $l -NoNewline
    $SchematicContent | Set-Content -LiteralPath $s -NoNewline
    $top = if ($LayoutContent -match '\.(?:SUBCKT|subckt)\s+(\w+)') { $matches[1] } else { "" }
    "layout: $l`nschematic: $s`ntop: $top" | Set-Content -LiteralPath $j -NoNewline
    & $VygesBin run $j --json -o $o 2>$null
    if (Test-Path $o) { return (Get-Content -LiteralPath $o -Raw | ConvertFrom-Json) }
    return $null
  } finally { Remove-TempDir $tmp }
}

function Run-Test {
  param([string]$Name, [string]$Category, [string]$Schematic, [string]$Expect)
  $script:testCount++
  Write-Host ""
  Write-Host ("=" * 65) -ForegroundColor DarkGray
  Write-Host ("[{0}] {1}" -f $script:testCount, $Name) -ForegroundColor Cyan
  Write-Host ("  Category: {0} | Expected: {1}" -f $Category, $Expect) -ForegroundColor DarkGray

  $vyges = Run-Vyges -LayoutContent $LAYOUT -SchematicContent $Schematic
  $vMatch = if ($vyges -and $vyges.matched) { "MATCH" } else { "MISMATCH" }

  # name-based via node inline
  $nameBased = node --import tsx -e @"
import { compareByName } from './backend/src/lib/compareByName.js';
const layout = JSON.parse(process.argv[1]);
const schematic = JSON.parse(process.argv[2]);
const r = compareByName(layout, schematic);
const mismatches = r.details.mismatchedDevices.map(d => d.name + ':' + d.reason).join(',');
const unbal = r.unbalanced.filter(u => u.what === 'device')
  .map(u => (u.a.length?'L:'+u.a.join(','):'') + (u.b.length?' S:'+u.b.join(','):'')).join(' | ');
console.log(JSON.stringify({matched: r.matched, devCount: r.a_devices, mismatches, unbal}));
"@ -- $(ConvertTo-Json -Compress $LAYOUT) $(ConvertTo-Json -Compress $Schematic) 2>$null

  $nb = if ($nameBased) { $nameBased | ConvertFrom-Json } else { $null }
  $nMatch = if ($nb -and $nb.matched) { "MATCH" } else { "MISMATCH" }

  $verdict = if ($vMatch -eq $Expect -or $nMatch -eq $Expect) { "PASS" } else { "FAIL" }
  $agree = if ($vMatch -eq $nMatch) { "agree" } else { "DISCREPANCY" }

  Write-Host ("  vyges-lvs: {0} | name-based: {1} | {2}" -f $vMatch, $nMatch, $agree) -ForegroundColor $(if ($agree -eq "agree") { "Green" } else { "Yellow" })
  if ($nb) {
    if ($nb.mismatches) { Write-Host ("  name-based mismatches: {0}" -f $nb.mismatches) -ForegroundColor DarkGray }
    if ($nb.unbal) { Write-Host ("  name-based unbalanced: {0}" -f $nb.unbal) -ForegroundColor DarkGray }
    Write-Host ("  name-based devices: {0}" -f $nb.devCount) -ForegroundColor DarkGray
  }
  if ($vyges -and $vyges.unbalanced) {
    $dUnbal = $vyges.unbalanced | Where-Object { $_.what -eq "device" }
    if ($dUnbal) { foreach ($u in $dUnbal) { Write-Host ("  vyges-lvs unbalanced: L=$($u.a_count) S=$($u.b_count)") -ForegroundColor DarkGray } }
  }

  Write-Host ("  >> {0}" -f $verdict) -ForegroundColor $(if ($verdict -eq "PASS") { "Green" } else { "Red" })
  if ($verdict -eq "PASS") { $script:passCount++ } else { $script:failCount++ }
  $script:results += @{Name=$Name; Category=$Category; Expected=$Expect; vMatch=$vMatch; nMatch=$nMatch; Verdict=$verdict}
}

# ══════════════════════════════════════════════════════════════
# TEST CASES
# ══════════════════════════════════════════════════════════════

# 1. MATCH baseline
Run-Test -Name "Identical layout (self)" -Category "MATCH" -Schematic $LAYOUT -Expect "MATCH"
Run-Test -Name "Renamed nets schematic" -Category "MATCH" -Schematic $SCHEMATIC -Expect "MATCH"

# 2. TYPE MISMATCH (same name, different type)
$t1 = $SCHEMATIC -replace "Q7 .+pnp", "Q7 (n8 n22 n23 0) npn"
Run-Test -Name "Q7 pnp→npn (type mismatch)" -Category "TYPE" -Schematic $t1 -Expect "MISMATCH"

$t2 = $SCHEMATIC -replace "R1 .+resistor r=3981", "R1 (n5 n6) capacitor c=10p"
Run-Test -Name "R1 resistor→capacitor (type mismatch)" -Category "TYPE" -Schematic $t2 -Expect "MISMATCH"

$t3 = $SCHEMATIC -replace "Q3 .+pnp m=5", "Q3 (n13 n14 n15 0) npn m=5"
Run-Test -Name "Q3 pnp→npn (type mismatch)" -Category "TYPE" -Schematic $t3 -Expect "MISMATCH"

# 3. CONNECTION MISMATCH (same name, different terminals)
$c1 = $SCHEMATIC -replace "R2 \(n1 n2\)", "R2 (n2 n1)"
Run-Test -Name "R2 terminals swapped" -Category "CONNECTION" -Schematic $c1 -Expect "MISMATCH"

$c2 = $SCHEMATIC -replace "Q10 \(n29 n30 n31 0\)", "Q10 (n29 n35 n31 0)"
Run-Test -Name "Q10 one terminal changed" -Category "CONNECTION" -Schematic $c2 -Expect "MISMATCH"

$c3 = $SCHEMATIC -replace "Q7 \(n8 n22 n23 0\)", "Q7 (n23 n22 n8 0)"
Run-Test -Name "Q7 collector/emitter swapped" -Category "CONNECTION" -Schematic $c3 -Expect "MISMATCH"

# 4. NAME SWAP (Q7↔Q9, different types)
$n1 = $SCHEMATIC
$n1 = $n1 -replace "Q7 \(n8 n22 n23 0\) pnp", "Q9TEMP (n8 n22 n23 0) pnp"
$n1 = $n1 -replace "Q9 \(n25 n26 n27 0\) npn m=1.29", "Q7 (n8 n22 n23 0) pnp"
$n1 = $n1 -replace "Q9TEMP \(n8 n22 n23 0\) pnp", "Q9 (n25 n26 n27 0) npn m=1.29"
Run-Test -Name "Q7↔Q9 swapped (different types)" -Category "NAME_SWAP" -Schematic $n1 -Expect "MISMATCH"

# 5. EXTRA / MISSING DEVICES
$x1 = $SCHEMATIC -replace "R6 \(n9 n8\) resistor r=3981\n", ""
Run-Test -Name "R6 removed from schematic" -Category "EXTRA" -Schematic $x1 -Expect "MISMATCH"

$x2 = $SCHEMATIC + "  R99 (n1 GND) resistor r=1k\n"
Run-Test -Name "R99 added to schematic" -Category "EXTRA" -Schematic $x2 -Expect "MISMATCH"

$x3 = $SCHEMATIC -replace "R2 \(n1 n2\) resistor r=3981\n", ""
Run-Test -Name "R2 removed from schematic" -Category "EXTRA" -Schematic $x3 -Expect "MISMATCH"

# 6. PARAM CHANGED (topology MATCH, params differ)
$p1 = $SCHEMATIC -replace "R1 .+r=3981", "R1 (n5 n6) resistor r=5000"
Run-Test -Name "R1 r=3981→5000 (param)" -Category "PARAM" -Schematic $p1 -Expect "MATCH"

$p2 = $SCHEMATIC -replace "Q3 .+m=5", "Q3 (n13 n14 n15 0) pnp m=10"
Run-Test -Name "Q3 m=5→10 (param)" -Category "PARAM" -Schematic $p2 -Expect "MATCH"

$p3 = $SCHEMATIC -replace "C1 .+c=34570.868f", "C1 (n36 n37) capacitor c=40000f"
Run-Test -Name "C1 c=34.5p→40p (param)" -Category "PARAM" -Schematic $p3 -Expect "MATCH"

# 7. NAME VARIANT + OVERLAP (Q10→Q100 with renamed terminal)
$o1 = $SCHEMATIC -replace "Q10 \(n29 n30 n31 0\) npn m=1.06", "Q100 (n29 n35 n31 0) npn m=1.06"
Run-Test -Name "Q10→Q100 + terminal renamed (overlap)" -Category "OVERLAP" -Schematic $o1 -Expect "MISMATCH"

$o2 = $SCHEMATIC -replace "R6 \(n9 n8\) resistor r=3981", "R66 (n9 n8) resistor r=3981"
Run-Test -Name "R6→R66 same connections (name variant)" -Category "OVERLAP" -Schematic $o2 -Expect "MISMATCH"

# 8. GLOBAL NET VARIATIONS
$g1 = $SCHEMATIC -replace "VDD GND", "VCC GND"
Run-Test -Name "VDD→VCC in schematic (global rename)" -Category "GLOBAL" -Schematic $g1 -Expect "MATCH"

# 9. MULTIPLE ERRORS COMBINED
$m1 = $SCHEMATIC
$m1 = $m1 -replace "R2 \(n1 n2\) resistor r=3981", "R2 (n1 n5) resistor r=3981"  # terminal changed
$m1 = $m1 -replace "R6 \(n9 n8\) resistor r=3981", ""  # R6 removed
$m1 = $m1 -replace "Q10 \(n29 n30 n31 0\) npn m=1.06", "Q100 (n29 n35 n31 0) npn m=2.0"  # rename + param
Run-Test -Name "Combined: R2 conn + R6 missing + Q10→Q100 param" -Category "COMBINED" -Schematic $m1 -Expect "MISMATCH"

# 10. EDGE: DIODE / CAP / RESISTOR overlap
$e1 = $SCHEMATIC -replace "C1 \(n36 n37\) capacitor c=34570.868f", "C1 (n36 n37) capacitor c=35000f"
Run-Test -Name "C1 c=34.57p→35p minor param" -Category "EDGE" -Schematic $e1 -Expect "MATCH"

$e2 = $SCHEMATIC -replace "R8 \(n31 n38\) resistor r=3887", "R88 (n31 n38) resistor r=3887"
Run-Test -Name "R8→R88 same conn (name variant)" -Category "EDGE" -Schematic $e2 -Expect "MISMATCH"

$e3 = $SCHEMATIC -replace "R9 \(GND n39\) resistor r=3887", "R9 (GND n39) resistor r=5000"
Run-Test -Name "R9 r=3887→5000 (param)" -Category "EDGE" -Schematic $e3 -Expect "MATCH"

$e4 = $SCHEMATIC -replace "Q101 .+npn m=1.13", "Q101 (n10 n11 GND 0) npn m=2.5"
Run-Test -Name "Q101 m=1.13→2.5 (param)" -Category "EDGE" -Schematic $e4 -Expect "MATCH"

# 11. EMPTY schematic
Run-Test -Name "Empty schematic" -Category "EDGE" -Schematic "" -Expect "MISMATCH"

# ══════════════════════════════════════════════════════════════
# SUMMARY
# ══════════════════════════════════════════════════════════════
Write-Host ""
Write-Host ("=" * 65) -ForegroundColor Cyan
Write-Host "COMPREHENSIVE LVS TEST SUMMARY" -ForegroundColor Cyan
Write-Host ("=" * 65) -ForegroundColor Cyan
Write-Host ("Total:  {0}" -f $testCount)
Write-Host ("Passed: {0}" -f $passCount) -ForegroundColor $(if ($passCount -eq $testCount) { "Green" } else { "Yellow" })
Write-Host ("Failed: {0}" -f $failCount) -ForegroundColor $(if ($failCount -eq 0) { "Green" } else { "Red" })
Write-Host ""
Write-Host "Per-Category:" -ForegroundColor Cyan
$cats = $results | Group-Object Category
foreach ($c in $cats) {
  $okCount = ($c.Group | Where-Object { $_.Verdict -eq "PASS" }).Count
  $total = $c.Count
  $col = if ($okCount -eq $total) { "Green" } else { "Red" }
  Write-Host ("  {0,-15} {1,2}/{2,2} pass" -f $c.Name, $okCount, $total) -ForegroundColor $col
}
Write-Host ""
Write-Host "Detail:" -ForegroundColor DarkGray
foreach ($r in $results) {
  $agree = if ($r.vMatch -eq $r.nMatch) { "✓" } else { "✗" }
  Write-Host ("  [{0,-10}] {1,-50} v={2,-7} n={3,-7} {4}" -f $r.Verdict, $r.Name, $r.vMatch, $r.nMatch, $agree) -ForegroundColor DarkGray
}
