/**
 * analogExport.ts — Backend API for analog netlist export.
 *
 * Endpoints:
 *   POST /api/dies/:dieId/analog-export  — generate SPICE/CDL netlist
 *   POST /api/dies/:dieId/spice-config   — save SPICE technology config
 *   GET  /api/dies/:dieId/spice-config   — load SPICE technology config
 *
 * The frontend runs device detection (analogDevices.ts), then submits the
 * device list here for export file generation. This keeps heavy geometry
 * processing on the client and leaves the backend as the file store.
 */

import { promises as fs } from "node:fs";
import path from "node:path";
import { Router } from "express";
import type { AnalogDevice, AnalogExportRequest, AnalogExportResponse, SpiceConfig } from "shared";
import { readDieRecord } from "../store.js";

/**
 * In-memory cache: dieId → SpiceConfig.
 * Persisted to data/dies/<dieId>/spice_config.json
 */
async function loadSpiceConfig(dataRoot: string, dieId: string): Promise<SpiceConfig | null> {
  try {
    const p = path.join(dataRoot, "dies", dieId, "spice_config.json");
    const raw = await fs.readFile(p, "utf8");
    return JSON.parse(raw) as SpiceConfig;
  } catch {
    return null;
  }
}

async function saveSpiceConfig(
  dataRoot: string,
  dieId: string,
  config: SpiceConfig,
): Promise<void> {
  const dir = path.join(dataRoot, "dies", dieId);
  await fs.mkdir(dir, { recursive: true });
  await fs.writeFile(
    path.join(dir, "spice_config.json"),
    JSON.stringify(config, null, 2),
    "utf8",
  );
}

// ═════════════════════════════════════════════════════════════════
// SPICE/CDL file generator (backend version)
// ═════════════════════════════════════════════════════════════════

const INSTANCE_PREFIXES: Record<string, string> = {
  mos: "M", bjt_npn: "Q", bjt_pnp: "Q",
  jfet_n: "J", jfet_p: "J",
  resistor: "R", capacitor: "C",
  diode: "D", zener: "D", schottky: "D",
  inductor: "L", unknown: "X",
};

function sanitize(name: string): string {
  const s = name.replace(/[^A-Za-z0-9_]/g, "_");
  return /^[0-9]/.test(s) ? `n_${s}` : s || "n";
}

function assignInstanceNames(devices: AnalogDevice[]): AnalogDevice[] {
  const counters = new Map<string, number>();
  return devices.map((d) => {
    const prefix = INSTANCE_PREFIXES[d.kind] || "X";
    const count = (counters.get(prefix) ?? 0) + 1;
    counters.set(prefix, count);
    return { ...d, instanceName: `${prefix}${count}` };
  });
}

function netName(netId: number, named: Map<number, string>): string {
  if (netId < 0) return "0";
  return named.get(netId) ?? `n${netId}`;
}

function terminalStr(
  kind: string,
  terminals: { name: string; netId: number }[],
  named: Map<number, string>,
): string {
  const tn = (name: string) => {
    const t = terminals.find((t) => t.name === name);
    return t ? netName(t.netId, named) : "0";
  };
  switch (kind) {
    case "mos": return `${tn("D")} ${tn("G")} ${tn("S")} ${tn("B")}`;
    case "bjt_npn": case "bjt_pnp": return `${tn("C")} ${tn("B")} ${tn("E")}`;
    case "jfet_n": case "jfet_p": return `${tn("D")} ${tn("G")} ${tn("S")}`;
    default: return `${tn("PLUS")} ${tn("MINUS")}`;
  }
}

function generateCDL(
  devices: AnalogDevice[],
  moduleName: string,
  named: Map<number, string>,
  vdd: string,
  gnd: string,
): string {
  const lines: string[] = [];
  lines.push(`* SPICE netlist generated by mmo-chip analog export`);
  lines.push(`* Module: ${moduleName}`);
  lines.push(`.GLOBAL ${vdd} ${gnd}`);
  lines.push("");

  // Collect ports (unique net names excluding VDD/GND/0)
  const portSet = new Set<string>();
  for (const d of devices) {
    const ts = terminalStr(d.kind, d.terminals, named);
    for (const tok of ts.split(" ")) {
      const t = tok.trim();
      if (t && t !== "0" && t !== vdd && t !== gnd) portSet.add(t);
    }
  }
  const ports = [...portSet].sort();
  lines.push(`.SUBCKT ${sanitize(moduleName)} ${ports.join(" ")} ${vdd} ${gnd}`);

  for (const d of devices) {
    const ts = terminalStr(d.kind, d.terminals, named);
    const params: string[] = [];
    const g = d.geometry as Record<string, unknown>;

    switch (d.kind) {
      case "mos":
        if (typeof g.W_um === "number" && g.W_um > 0) params.push(`W=${(g.W_um as number).toFixed(2)}U`);
        if (typeof g.L_um === "number" && g.L_um > 0) params.push(`L=${(g.L_um as number).toFixed(2)}U`);
        if (typeof g.multiplier === "number" && g.multiplier > 1) params.push(`M=${g.multiplier}`);
        if (typeof g.fingers === "number" && g.fingers > 1) params.push(`NF=${g.fingers}`);
        break;
      case "bjt_npn": case "bjt_pnp":
        if (typeof g.AE_um2 === "number" && g.AE_um2 > 0) params.push(`AREA=${(g.AE_um2 * 1e-12).toExponential(2)}`);
        break;
      case "resistor":
        if (typeof g.resistance_ohms === "number" && g.resistance_ohms > 0) params.push(`R=${(g.resistance_ohms as number).toFixed(1)}`);
        else if (typeof g.W_um === "number" && typeof g.L_um === "number") {
          params.push(`W=${(g.W_um as number).toFixed(2)}U L=${(g.L_um as number).toFixed(2)}U`);
        }
        break;
      case "capacitor":
        if (typeof g.capacitance_fF === "number" && g.capacitance_fF > 0) params.push(`C=${(g.capacitance_fF as number).toFixed(3)}F`);
        else if (typeof g.area_um2 === "number" && g.area_um2 > 0) params.push(`C=${(g.area_um2 * 1e-15).toExponential(2)}`);
        break;
    }

    const model = d.modelName ?? `${d.kind.toUpperCase()}_GEN`;
    const paramStr = params.length > 0 ? ` ${params.join(" ")}` : "";
    lines.push(`  ${d.instanceName ?? d.id} ${ts} ${model}${paramStr}`);
  }

  lines.push(`.ENDS ${sanitize(moduleName)}`);
  return lines.join("\n");
}

// ═════════════════════════════════════════════════════════════════
// Express router
// ═════════════════════════════════════════════════════════════════

export function createAnalogExportRouter(config: { dataRoot: string }) {
  const router = Router();

  /**
   * POST /api/dies/:dieId/analog-export
   *
   * Body: {
   *   devices: AnalogDevice[],
   *   dialect: "cdl" | "spectre" | "hspice",
   *   hierarchical: boolean,
   *   moduleName?: string,
   *   spiceConfig?: SpiceConfig,
   *   netNames?: Record<string, string>,  // netId → human name
   * }
   *
   * Response: { netlistPath, deviceCount, byKind, warnings }
   */
  router.post("/api/dies/:dieId/analog-export", async (request, response, next) => {
    const { dieId } = request.params;
    try {
      // Validate die exists
      const die = await readDieRecord(config.dataRoot, dieId);

      const body = request.body ?? {};
      const devices: AnalogDevice[] = body.devices ?? [];
      const dialect: string = body.dialect ?? "cdl";
      const hierarchical: boolean = body.hierarchical ?? false;
      const moduleName: string = sanitize(body.moduleName ?? die.name);
      const configOverride: SpiceConfig | undefined = body.spiceConfig;
      const netNamesRaw: Record<string, string> | undefined = body.netNames;

      if (devices.length === 0) {
        response.status(400).json({ error: "No devices provided" });
        return;
      }

      // Merge saved config with request override
      const savedConfig = await loadSpiceConfig(config.dataRoot, dieId);
      const spiceConfig: SpiceConfig = {
        ...savedConfig,
        ...configOverride,
      };

      // Build net name map
      const named = new Map<number, string>();
      if (netNamesRaw) {
        for (const [netId, name] of Object.entries(netNamesRaw)) {
          named.set(Number(netId), name);
        }
      }
      // Also collect names from device terminals
      for (const d of devices) {
        for (const t of d.terminals) {
          if (t.netId >= 0 && !named.has(t.netId)) {
            named.set(t.netId, `net${t.netId}`);
          }
        }
      }

      // Assign instance names
      const namedDevices = assignInstanceNames(devices);

      // Generate netlist
      const vdd = spiceConfig.vdd ?? "VDD";
      const gnd = spiceConfig.gnd ?? "GND";
      let netlist: string;
      switch (dialect) {
        case "spectre":
          netlist = generateCDL(namedDevices, moduleName, named, vdd, gnd);
          break;
        case "hspice":
          netlist = generateCDL(namedDevices, moduleName, named, vdd, gnd);
          break;
        default:
          netlist = generateCDL(namedDevices, moduleName, named, vdd, gnd);
      }

      // Write output file
      const exportDir = path.join(config.dataRoot, "dies", dieId, "export");
      await fs.mkdir(exportDir, { recursive: true });
      const ext = dialect === "spectre" ? "scs" : "cdl";
      const netlistPath = path.join(exportDir, `${moduleName}.${ext}`);
      await fs.writeFile(netlistPath, netlist, "utf8");

      // Count by kind
      const byKind: Record<string, number> = {};
      for (const d of devices) {
        byKind[d.kind] = (byKind[d.kind] ?? 0) + 1;
      }

      const result: AnalogExportResponse = {
        netlistPath,
        deviceCount: devices.length,
        byKind,
        warnings: [],
      };

      response.status(200).json(result);
    } catch (error) {
      next(error);
    }
  });

  /**
   * POST /api/dies/:dieId/spice-config
   *
   * Save SPICE technology configuration for a die.
   */
  router.post("/api/dies/:dieId/spice-config", async (request, response, next) => {
    const { dieId } = request.params;
    try {
      await readDieRecord(config.dataRoot, dieId);
      const sc = request.body as SpiceConfig;
      await saveSpiceConfig(config.dataRoot, dieId, sc);
      response.json({ ok: true });
    } catch (error) {
      next(error);
    }
  });

  /**
   * GET /api/dies/:dieId/spice-config
   *
   * Load saved SPICE technology configuration.
   */
  router.get("/api/dies/:dieId/spice-config", async (request, response, next) => {
    const { dieId } = request.params;
    try {
      await readDieRecord(config.dataRoot, dieId);
      const sc = await loadSpiceConfig(config.dataRoot, dieId);
      response.json(sc ?? {});
    } catch (error) {
      next(error);
    }
  });

  /**
   * PUT /api/dies/:dieId/analog-layers
   *
   * Save die-level analog layer annotations (CellLayers).
   * Reads current annotations, replaces analogLayers, writes back.
   */
  router.put("/api/dies/:dieId/analog-layers", async (request, response, next) => {
    const { dieId } = request.params;
    try {
      await readDieRecord(config.dataRoot, dieId);
      const { readAnnotations, writeAnnotations } = await import("../store.js");
      const annotations = await readAnnotations(config.dataRoot, dieId);
      annotations.analogLayers = request.body ?? {};
      const rev = await writeAnnotations(config.dataRoot, dieId, annotations);
      response.json({ ok: true, rev });
    } catch (error) {
      next(error);
    }
  });

  return router;
}
